Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 4096 
    libvirt.cpus = 4
  end

  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.hostname = "scanMe"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "scripts/playbook.yml"
    ansible.groups = {
        "all:vars" => {
        "ansible_python_interpreter" => "auto_silent"
        }
    }
  end
end